<div id="sitecontent">
  <div class="wrapper1">
    <form id="contact-form" class="styled-form" action="" method="post" accept-charset="utf-8">
      <div style="display:none"><input name="csrfmiddlewaretoken" value="8ece95d139633656ad0371bf53c45b2d" type="hidden"></div>    
      <h1 class="pagetitle">Contact us</h1>
      <div class="note">
        <p class="firstp">We are here to answer any questions you may have about our Ziffysupply
        experiences. Reach out to us and we'll respond as soon as we can.</p>
        <p class="firstp">Even if there is something you have always wanted to experience and
        can't find it with us, let us know and we promise we'll do our
        best to find it for you.</p>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <p class="row half first firstp">
            <label for="id_name">Name: <span class="required">*</span></label>
            <span class="field"><input name="name" id="id_name" type="text"></span>
          </p>
          <p class="row half first firstp">
            <label for="id_email">Email: <span class="required">*</span></label>
            <span class="field"><input name="email" id="id_email" type="text"></span>
          </p>
          <p class="row half first firstp">
            <label for="id_mobile">Mobile: <span class="required">*</span></label>
            <span class="field"><input name="mobile" id="id_mobile" type="text"></span>
          </p>
        </div>
        <div class="col-sm-6 contact-message">
          <p class="row half firstp">
            <label for="id_message">Message: <span class="required">*</span></label>
            <span class="field"><textarea cols="40" rows="5" name="message" id="id_message"></textarea></span>
          </p>
        </div>
      </div>
      <!--<p class="row half first">
        <label for="id_tapcha_0">How much is 5+7? <span class="required">*</span></label>
        <span class="field"><input name="tapcha_0" id="id_tapcha_0" type="text"><input name="tapcha_1" id="id_tapcha_1" value="Nzg0MTEwMjcyZGRhOWUyZTRmZWM0YTE0OTRhMDM2MTUxNzliOWIzZQ==" type="hidden"></span>
        <span style="display:none">
          <span class="field"><input name="honeypot" id="id_honeypot" type="text"></span>
        </span>
      </p>-->
      <p class="submit-row">
        <button type="submit">SEND</button>
      </p>
    </form>
    <aside id="contact-info">
      <dl>
        <dt>Email</dt>
        <dd><a href="mailto:info@combadi.com" title="Click to send us an email">hello@ziffysupply.com</a></dd>
        <dt>Telephone</dt>
        <dd><a href="tel:00306977447033" title="Click to call us">+91 91675 58548</a></dd>
        <dt>Skype</dt>
        <dd><a href="skype:ziffysupply?call" title="Click to call us on Skype">ziffysupply</a></dd>
        <dt>Address</dt>
        <dd>
          <address>
            Shop No.411<br>
            Arya Arcade<br>
            Vikhroli West<br>
            Mumbai<br>
            Maharashtra - 400083<br><br>
          </address>
        </dd>
        <dd class="social-links">
          <a class="fb" href="http://www.facebook.com/Ziffysupply" title="Find us on Facebook">Facebook</a>
          <a class="tt" href="http://twitter.com/ziffysupply" title="Find us on Twitter">Twitter</a>
        </dd>
      </dl>
    </aside>
  </div>
</div>