<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();

    $_infoblock = Mage::getStoreConfig('porto_settings/contacts/infoblock', $code);
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="row container">
    <div class="privacypage-header">
        <h2 class="privacy-heading">Contact Us</h2>
    </div>
    
    <div class="col-sm-6">
        <div id="sitecontent">
            <div class="wrapper1 styled-form" id="contact-form">    
                <div class="note">
                    <p class="firstp">We are here to answer any questions you may have about our Ziffysupply experiences. Reach out to us and we'll respond as soon as we can.</p>
                    <p class="firstp">Even if there is something you have always wanted to experience and can't find it with us, let us know and we promise we'll do our best to find it for you.</p>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            //<![CDATA[
                var RecaptchaOptions = {
                    theme : '<?php echo $this->getCaptchaTheme(); ?>',
                    lang : '<?php echo $this->getCaptchaLang(); ?>',
                };
            //]]>
        </script>
        <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
            <h2 class="legend legend1"><b><?php echo Mage::helper('contacts')->__('Leave') ?> <?php echo Mage::helper('contacts')->__('Comment') ?></b></h2>
            <div class="row">
                <ul class="form-list col-sm-6">
                    <li>
                        <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                        <div class="input-box1">
                            <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                        </div>
                    </li>
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                        <div class="input-box1">
                            <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                        </div>
                    </li>
                    <li>
                        <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                        <div class="input-box1">
                            <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text" type="text" />
                        </div>
                    </li>
                </ul>
                <ul class="form-list col-sm-6">
                    <li>
                        <label for="comment" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                        <div class="input-box1 input-textarea">
                            <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text" cols="5" rows="5" placeholder="<?php echo Mage::helper('contacts')->__('Comment') ?>"></textarea>
                        </div>
                    </li>
                    <li class="wide">
                        <div class="input-box">
                            <?php echo $this->getCaptchaCode(); ?>
                        </div>
                    </li>
                    <li class="submitbutton">
                        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button button1"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
                    </li>
                </ul>
            </div>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var contactForm = new VarienForm('contactForm', true);
        //]]>
        </script>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-4 contact-info">
        <h2 class="legend"><b><?php echo Mage::helper('contacts')->__('Contact') ?> <?php echo Mage::helper('contacts')->__('Details') ?></b></h2>
        <?php
            echo $_infoblock;
        ?>
    </div>
</div><br/>
<div class="privacypage-header"></div>