<div class="container">
	<div class="privacypage-header">
		<h2 class="privacy-heading">About Us</h2>
	</div><br/>
	<div class="para-content">
		Buildmatic started with the aim of easing the Construction Materials and Services procurement process by 
		increasing the range of materials and services available at one single place in a transparent manner.
	</div><br/>
	<div class="para-content">
		We derive our strength and pride from our highly passionate founding team with 
		backgrounds from IIM Ahmedabad and IIT and relevant construction industry experience.
	</div><br/>
	<div class="para-content">
		We are constantly looking for people who have the passion, drive and ability in various 
		streams such as technology, supply chain and operations. 
		<ul>
			<li>• If you want to join our growing team, please write to us at <a style="color: #1B95E0;" href="mailto:hr@buildmatic.in">hr@buildmatic.in</a>.</li>
			<li>• If you want to become our supply partner, please write to us at <a style="color: #1B95E0;" href="mailto:partner@Buildmatic.in">partner@buildmatic.in</a> or register by calling us.</li>
		</ul>
	</div>
</div><br/>
<div class="privacypage-header"></div>