<div class="container">
	<div class="privacypage-header">
		<h1 class="privacy-heading">About Us</h1>
	</div><br/>
	<div class="para-content">
		ZiffySupply is a company started in 2015 with the aim of easing your procurement process by 
		increasing the range of products available at your door step and bringing transparency to the 
		procurement pricing process.
	</div><br/>
	<div class="para-content">
		We derive our strength and pride from our highly passionate founding team with a 
		background from IIM Ahmedabad and IIT.
	</div><br/>
	<div class="para-content">
		We are constantly looking for people who have the passion, drive and ability in various 
		streams such as technology, supply chain and operations. 
		<ul>
			<li>• If you want to join our growing team, please write to us at <a href="mailto:hr@ziffysupply.com">hr@ziffysupply.com</a>.</li>
			<li>• If you want to become our supply partner, please write to us at <a href="mailto:partner@ziffysupply.com">partner@ziffysupply.com</a> or register <a href="hr@ziffysupply.com">here.</li>
		</ul>
	</div>
</div>