<div class="container">
	<div class="privacypage-header">
		<h2 class="privacy-heading">Cancellation and Refund Policy</h2>
	</div>
	<div>
		<strong>1.	Cancellations</strong>
		<ul>
			<li>
				a.	Cancellation by User: We will be glad to assist you with a cancellation of your order provided the order has not already shipped out. In case the order has shipped out, the order cannot be cancelled. In exceptional cases, we may allow cancellation of your specific order subject to forfeiture of any costs incurred in shipping process.
			</li>
			<li>
				b.	Cancellation by ZiffySupply: ZiffySupply may cancel your order in the following exceptional cases
				<ul>
					<li>i.	Product no longer available or out of stock.</li>
					<li>ii.	Product has been discontinued.</li>
					<li>iii. Location cannot be serviced.</li>
					<li>iv.	Order not in compliance with the Terms of Use of our website.</li>
					<li>v. Any Force Majeure event.</li>
				</ul>
			</li>
		</ul>
	</div>
	<div>
		<strong>2.	What is the process of cancellation of a product ?</strong><br/>
		<p>If you have already placed an order and would like to cancel an order for some reason, you can simply send us a mail at <a href="support@ziffysupply.com">support@ziffysupply.com</a> from your registered ID with the details of your Order ID.</p>
	</div>
	<div>
		<strong>3.	What is the process for replacement or return of a product ?</strong><br/>
		<p>Replacement or Return of a product is a quick and hassle free process and must meet the following conditions</p>
		<ul>
			<li>a.	Product delievered differs from the product ordered as per details of the invoice.</li>
			<li>b.	Product delivered is either a defective or fault product.</li>
			<li>c.	Product being returned is in acceptable condition as per the conditions described below
				<ul>
					<li>i.	Product is in the original condition and should not have been used, altered or damaged.</li>
					<li>ii.	All original product labels, logo and packing completely intact.</li>
				</ul>
			</li>
		</ul>
	</div>
	<div>
		<strong>4.	What is the process of return or replacement of a product ?</strong><br/>
		<p>In case you have received a faulty or damaged product, you can contact us within 5 days of receiving the order by mailing us at <a href="support@ziffysupply.com">support@ziffysupply.com</a> from your registered ID with the details of your Order ID, issue being faced and photos showing the nature of issue with the product.</p>
	</div>
	<div>
		<strong>5.	Refunds</strong><br/>
		<p>We endevaor to make your procurement experience a hassle free one. If you are not satisfied with your product for some reason and have returned the product, our operations team will verify the returned products. If everything is in order, we will initiate your refund. You will receive a payment refund with 7-10 days after you receive a confirmation of refund from our side. We will need the following details from your end to process the refund request.</p><br/>
		<ul>
			<li>•	Bank Name and Location</li>
			<li>•	Account Number</li>
			<li>•	Account Holders Name</li>
			<li>•	IFSC Code</li>
		</ul>
	</div>
</div>
