<div class="container-flex">
	<div class="color-callout light-blue color-callout--pull-up">
		<h2 class="soft-header soft-header--small">
			We are growing and we need you !
		</h2>
		<p class="color-callout__tiny-copy">
			<div class="mbottom">We are constantly looking for people who have the passion, drive and ability in various streams such as technology, supply chain and operations.</div>
			If you want to join our passionate team, please write to us at <a href="hr@ziffysupply.com">hr@ziffysupply.com</a>
		</p>
	</div>
</div>