<?php
  $store = Mage::app()->getStore();
  $code  = $store->getCode();
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="container">
  <div class="privacypage-header">
    <h2 class="privacy-heading">Contact Us</h2>
  </div>
  
        <div class="row">
          <div class="col-sm-5">
            <p class="row half first firstp">
              <label for="id_name">Name: <span class="required">*</span></label>
              <span class="field"><input name="name" id="id_name" type="text"></span>
            </p>
            <p class="row half first firstp">
              <label for="id_email">Email: <span class="required">*</span></label>
              <span class="field"><input name="email" id="id_email" type="text"></span>
            </p>
            <p class="row half first firstp">
              <label for="id_mobile">Mobile: <span class="required">*</span></label>
              <span class="field"><input name="mobile" id="id_mobile" type="text"></span>
            </p>
          </div>
          <div class="col-sm-7 contact-message">
            <p class="row half firstp">
              <label for="id_message">Message: <span class="required">*</span></label>
              <span class="field"><textarea cols="40" rows="5" name="message" id="id_message"></textarea></span>
            </p>
          </div>
          <div class="submit-row">
            <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
          </div>
        </div>
      </form>
      <aside id="contact-info">
        <div class="contact-info-header">Email</div>
        <div class="contact-info-value"><a href="mailto:hello@ziffysupply.com" title="Click to send us an email">hello@ziffysupply.com</a></div>
        <div class="contact-info-header">Telephone</div>
        <div class="contact-info-value"><a href="tel:9167558548" title="Click to call us">+91 91675 58548</a></div>
        <div class="contact-info-header">Skype</div>
        <div class="contact-info-value"><a href="skype:ziffysupply?call" title="Click to call us on Skype">ziffysupply</a></div>
        <div class="contact-info-header">Address</div>
        <div class="contact-info-value">
          <address>
            Shop No.411<br>
            Arya Arcade<br>
            Vikhroli West<br>
            Mumbai<br>
            Maharashtra - 400083<br><br>
          </address>
        </div>
        <div class="social-links">
          <a class="fb" href="http://www.facebook.com/Ziffysupply" title="Find us on Facebook" style="background-position:-60px 0; width:30px; height:30px;">Facebook</a>
          <a class="tt" href="http://twitter.com/ziffysupply" title="Find us on Twitter" style="background-position:0px 0; width:30px; height:30px;">Twitter</a>
          <a class="ln" href="http://twitter.com/ziffysupply" title="Find us on LinkedIn" style="background-position:-300px 0; width:30px; height:30px;">Twitter</a>
        </div>
      </aside>
    </div>
  </div>