<div class="container">
	<div class="privacypage-header">
		<h2 class="privacy-heading">Privacy Policy</h2>
	</div>
	<p>
		We take privacy protection very seriously and we set the highest standards in this regard. We value the trust you place in us. Please read this document regarding our privacy policy.
	</p><br/>
	<p>
		<em class="note-line">Note: Our privacy policy is subject to change time to time without notice. To make sure you are aware of the changes, please review this policy periodically. Also this privacy statement does not apply to our business partners, affiliates or other third parties. Please review the privacy statements of the other parties with whom you may interact.</em>
	</p><br/>
	<p>
		THIS DOCUMENT IS PUBLISHED AND SHALL BE CONSTRUED IN ACCORDANCE WITH THE PROVISIONS OF THE INFORMATION TECHNOLOGY (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE PERSONAL DATA OF INFORMATION) RULES, 2011 UNDER INFORMATION TECHNOLOGY ACT, 2000; THAT REQUIRE PUBLISHING OF THE PRIVACY POLICY FOR COLLECTION, USE, STORAGE AND TRANSFER OF SENSITIVE PERSONAL DATA OR INFORMATION.
	</p><br/>
	<h3 class="sub-head">What user or customer information does ZiffySupply.com collect?</h3>
	<ul class="cus-info-points">
		<li>
			1.	Your contact details such as customer name, email address, your ZiffySupply.com account password, phone number and shipping address
		</li>
		<li>
			2.	<em>Important: Your transaction or banking details such as credit card number, cardholder name, expiration date and CVV or other information as required for internet banking or other payment instruments is not &nbsp;&nbsp;&nbsp;&nbsp;held or stored by us but is held by our Payment Gateway partner. Our payment gateway partner is "VeriSign Secured" and "PCI-Compliant" which ensure the highest standards of safety and security for your &nbsp;&nbsp;&nbsp;&nbsp;information.</em>
		</li>
		<li>
			3.	Your previous orders and transactions including the product and pricing details, the date of purchase, transaction information, payment history etc.
		</li>
		<li>
			4.	Information from optional online surveys on our or third party sites (posted by ZiffySupply.com) which may include demographic information (like gender, age, income) as well as product and service &nbsp;&nbsp;&nbsp;&nbsp;preferences of users.
		</li>
		<li>
			5.	Cookies: Cookies is a piece of data stored by a website within a browser which enable the browser to remember information specific to a given user such as clicking particular buttons, logging in, or having &nbsp;&nbsp;&nbsp;&nbsp;read certain pages on our site. All leading Internet companies such as Amazon, Yahoo, Google and Facebook use cookies. You can set your browser to notify you when you are sent a cookie, and you can &nbsp;&nbsp;&nbsp;&nbsp;decide whether or not to accept it.
		</li>
		<li>
			6.	Your session log information on our site which includes your navigation within the site, source of traffic, IP address (from which we can approximately determine user location), browser type, browser &nbsp;&nbsp;&nbsp;&nbsp;language, operating system, date and time of request etc.
		</li>
		<li>
			7.	Third party sign in information shared on our website such as Facebook, Twitter, Pinterest sign in information
		</li>
		<li>
			8.	Email communication by any user or customer directly with ZiffySupply.com such as product enquiry, order and transaction related information, disputes or complaints etc.
		</li>
	</ul><br/>
	<p>
		Note: User generated content on the site shared by users via reviews, blogs, online chat or instant messages, discussion boards, forums, user testimonials etc. are not considered as personal information and is not subject to the terms of this privacy policy.
	</p><br/>
	<h3 class="sub-head">How does ZiffySupply.com utilize user or customer information?</h3>
	<p>
		We only collect user or customer information as required to conduct our business and to enable us to provide the best services to our users and customers. We do not sell or rent this information to third parties.
	</p><br/>
	<p>User or customer information (as defined above) will be used as described below:</p><br/>
	<ul class="cus-info-points">
		<li>
			1.	User and customer information will be sharable with our subsidiaries, affiliates and partners which are also involved in delivering the service to you as a customer in your buying process. We will also need &nbsp;&nbsp;&nbsp;&nbsp;to share some or all of your information as governed in the case of acquisitions by or mergers with other business entities.
		</li>
		<li>
			2.	We use some of the user and customer information defined above to understand customer behaviour and thus offer better and more relevant experiences to you. We use certain information in an &nbsp;&nbsp;&nbsp;&nbsp;aggregated form across users to compile statistical and demographical profiles for our business and marketing activities.
		</li>
		<li>
			3.	We use this information to inform you about offers and deals, new launches, information about products you have purchased, order and shipping status, as well as other promotional and informational &nbsp;&nbsp;&nbsp;&nbsp;content. We will provide you the option to opt-out of such services.
		</li>
		<li>
			4.	Cookies would be used to provide a customized experience to our users such as identifying recently viewed items (of interest to the user) as well as implementing wish list and cart features.
		</li>
		<li>
			5.	We use session log and traffic flow information to understand how users are interacting with our site and to make improvements. This will also be used by us to understand and analyze customer &nbsp;&nbsp;&nbsp;&nbsp;preferences, buying patterns and behaviour at an aggregate level.
		</li>
		<li>
			6.	We use IP address, traffic sources, user navigation across the site, browser and OS information etc. to measure overall site performance in terms of number of users, user engagement, time spent by users &nbsp;&nbsp;&nbsp;&nbsp;on the site etc.
		</li>
		<li>
			7.	We will need to use user or customer information in case required in aspects such as legal disputes or other legal processes; comply with any statutory or regulatory requirement; troubleshoot problems; &nbsp;&nbsp;&nbsp;&nbsp;detect and protect against error, fraud and other criminal or illegal activity; collect fees owed; enforce our terms and conditions; prevent abuse of our services; prevent violation of the rights of third parties, &nbsp;&nbsp;&nbsp;&nbsp;other users or the general public.
		</li>
	</ul><br/>
	<p>
		ZiffySupply.com provides all users with the opportunity to opt-out of receiving non-essential communications from us on behalf of our partners, and from us in general, after setting up an account. To remove your contact information from ZiffySupply.com, please write to us at <a href="mailto:hello@ziffysupply.com">hello@ziffysupply.com</a>
	</p></br/>
	<p>
		Questions regarding this statement should be directed to the following address: <a href="mailto:hello@ziffysupply.com">hello@ziffysupply.com</a>
	</p>
</div>
