<?php $_product = $this->getProduct() ?>
<!-- Vinu changes for adding mrp price only if value is present for product -->
<?php if($_product->getMrp_price()!= ''): ?>
	<span class="mrp-price view-page"><?php echo Mage::helper('core')->currency($_product->getMrp_price(),true,false); ?></span>
<?php endif; ?>
<!-- Vinu changes end -->
<?php echo $this->getPriceHtml($_product) ?>

<?php if ($_product->isAvailable()): ?>
	<p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
	<p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>

<?php echo $this->getChildHtml('product_type_data_extra') ?>
