<?php
/**
 * ITWebExperts
 *
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2013 ITWebExperts
 */
?>
<?php /* onkar<?php if ($this->isRequestEnabled()) : ?>
	<?php
	$buttonTitle = $this->__('Request for Quote');
	?>
	<button type="button" title="<?php echo $buttonTitle ?>" class="button btn-r4q" clickfunc="sendForm('<?php echo $this->getUrl('request4quote_front/quote/add') ?>')"><span><span><?php echo $buttonTitle ?></span></span></button>
<?php endif; ?> */?>

<!-- Vinu changes for getting bulk quote of product or RFQ button of product based on setting -->
<?php if ($this->isRequestEnabled() && $this->isRequestOrderDisabled()) : ?>
	<?php
	$buttonTitle = $this->__('Request for Quote');
	?>
	<button type="button" title="<?php echo $buttonTitle ?>" class="button btn-r4q" clickfunc="sendForm('<?php echo $this->getUrl('request4quote_front/quote/add') ?>')"><span class="prodButton"><span><?php echo $buttonTitle ?></span></span></button> <!--onkar-->
<?php elseif ($this->isRequestEnabled() && !$this->isRequestOrderDisabled()) : ?>
	<div class="bulk-quote" style="margin-top: 15px;">
		<?php if($this->isDiscountOffered()!= ''): ?>
			<?php echo "Upto ".$this->isDiscountOffered()." OFF for Bulk Orders on this product : " ; ?>
		<?php else: ?>
			<?php echo "For Bulk Enquiry on this product : " ; ?>
		<?php endif; ?>
		<?php
		$buttonTitle = $this->__('Get Quote');
		?>
		<button type="button" title="<?php echo $buttonTitle ?>" class="bulk-r4q" clickfunc="sendForm('<?php echo $this->getUrl('request4quote_front/quote/add') ?>')"><span class="prodButton"><span><?php echo $buttonTitle ?></span></span></button> <!--onkar-->
	</div>
<?php endif; ?>
<!-- Vinu changes for getting bulk quote button end -->