<?php 
	$brands = Mage::getModel('buildmatic_brands/brands')->load($this->getRequest()->getParam('id'));
	$_productCollection = Mage::getModel('catalog/product');
	$attr = $_productCollection->getResource()->getAttribute("manufacturer");
	if ($attr->usesSource()) 
	{
	    $manufacturer_id = $attr->getSource()->getOptionId($brands->getBrandName());
	}
	$_productCollection = $_productCollection->getCollection()->addAttributeToSelect('*')->addAttributeToFilter('manufacturer', $manufacturer_id);
?>
<div class="brandSpecification row">
	<?php /*<div class="brandName col-xs-12"><center><?php echo $brands->getBrandName(); ?></center></div> */ ?>
	<div>
		<?php /*if ($brands->getBrandImage()): 
			<li class="col-sm-3">
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$brands->getBrandImage(); ?>" width="200px" height="200px"/>
			</li>
			<li class="brandDescription col-md-9"><?php echo $brands->getDescription(); ?></li>
		*/?>
		<?php/* else: */ ?>
			<span class="brandDescription col-md-12"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$brands->getBrandImage(); ?>"/><?php echo "Description: " .$brands->getDescription(); ?></span>
		<?php /*endif; */?>
	</div>
</div>
<?php /*
	$catIds = array();
	foreach ($_productCollection as $_product)
	{	
		$catIds = array_merge($catIds, $_product->getCategoryIds());
	}
	$catIds = array_unique($catIds);
?>
<div class="sub-cat-list3">
    <ul class="list3 term-list" >
		<?php foreach ($catIds as $catId): 
		$_category = Mage::getModel('catalog/category')->load($catId);?>
			<li class="catItem3 term-item">
	            <h5 class="category-name parent-category3">
	            	<a id="filter2" class="text-color" href="javascript:void(0)" title="<?php echo $_category->getName(); ?>" onclick="change(this.$catId)">
	            		<?php echo $_category->getName(); ?>
	            	</a>
	            </h5>
	        </li>
	    <?php endforeach ?>
	</ul>
</div> 
<?php */?>
<?php echo $this->getLayout()->createBlock('buildmatic_brands/brands')->setData('product_collection', $_productCollection)->setTemplate('brands/product/list.phtml')->toHtml(); ?>
<?php /*
<script type="text/javascript">
	$("#itemsubcat").change(function(){
        var subcat=$("#category-name").val();
        $("#item").show();
        $("#item").load('list.php?subcat='+subcat);
    });
</script>
*/?>