<div class="mt-10">
	<?php 
		//$categories = Mage::getModel('catalog/category')->load(Mage::app()->getStore()->getRootCategoryId())->getChildrenCategories();
		$categories = Mage::getResourceModel('catalog/category_collection')->addAttributeToSelect('*')->addAttributeToFilter('is_active', 1)->addAttributeToFilter('parent_id', Mage::app()->getStore()->getRootCategoryId())->addAttributeToSort('position');
		foreach ($categories as $_category): 
	?>	
		<div class="row footer-categories">
			<div class="levelonecats">
				<?php /* 
				<a href="<?php echo $_category->getURL(); ?>" class="footer-cat text-color11" title="<?php echo $_category->getName() ?>"><?php echo $_category->getName() ?> : </a> */ ?>
				<a class="footer-cat text-color11" title="<?php echo $_category->getName() ?>"><?php echo $_category->getName() ?> : </a>
			</div>
			<?php $SubCategories = $_category->getChildrenCategories(); ?>
            <?php $i=0; foreach ($SubCategories as $SubCategory): ?>
                <?php if($i==0): ?>
					<a class="inside-link-first text-color11" href="<?php echo $SubCategory->getURL(); ?>" title="<?php echo $SubCategory->getName(); ?>"> <?php echo '&nbsp;'.$SubCategory->getName().'&nbsp;' ?> </a>
				<?php else: ?>
					<span class="inside-link text-color11"><span>|</span><a class="text-color11" href="<?php echo $SubCategory->getURL(); ?>" title="<?php echo $SubCategory->getName(); ?>"><?php echo '&nbsp;'.$SubCategory->getName().'&nbsp;'; ?></a></span>
				<?php endif; ?>
            <?php 
			$i++;
			endforeach ?>
		</div>
	<?php endforeach ?>
</div>