<ul class="clearfix" style="margin-bottom:15px;">
	<?php
		$categories = Mage::getModel('catalog/category')->load(Mage::app()->getStore()->getRootCategoryId())->getChildrenCategories();
		foreach ($categories as $_category):
	?>
		<li class="menu-item" style="list-style: none; float:left">
			<h2 class="levelonecats"><a href="<?php echo $_category->getURL(); ?>" title="<?php echo $_category->getName() ?>"><?php echo $_category->getName() ?></a></h2>
			<ul>
				<?php $SubCategories = $_category->getChildrenCategories(); ?>
            	<?php $i=0; foreach ($SubCategories as $SubCategory): ?>
                	<li>
						<a class="inside-link" href="<?php echo $SubCategory->getURL(); ?>" title="<?php echo $SubCategory->getName(); ?>"><?php echo $SubCategory->getName(); ?></a>
					</li>
				<?php 
					$i++;
					if($i==3) break;
				endforeach ?>
				<?php $i=0; foreach ($SubCategories as $SubCategory) { $i++; } ?>
				<?php if($i > 3): ?>
					<li class="w-all">
						<a class="lev" href="<?php echo $_category->getURL(); ?>"><?php echo $total_count=($i-3)." ".__('more..') ?></a>
					</li>
				<?php endif; ?>
			</ul>
		</li>
	<?php endforeach ?>
</ul>