<?php
/*
* List Sub catgories template
*/
?>

<?php
    $object = new Mage_Catalog_Block_Navigation();
    $categoyrId = 2;
    $actualCategory = Mage::getModel('catalog/category')->load($categoyrId);
    $subCategories = explode(',', $actualCategory->getChildren()); 
    $maxCategoryCount    = $this->getCategoryCount();
?>
<div class="sub-cat-list2">
	<h3 class="filter-title l-height70">
        <span class="content">
            <strong>Product Categories</strong>
        </span>
    </h3>
    <ul class="img-list2">
        <?php $i; foreach ($subCategories as $subCategoryId): $i++; ?>
            <?php if ($i > $maxCategoryCount): break; endif; ?>
            <?php 
        	   $category = Mage::getModel('catalog/category')->load($subCategoryId);
        	   if ($category->getIsActive() ): 
            ?>
        	    <li class="catItem2">
                    <div class="catbox2">
                        <h5 class="category-name parent-category2"><a class="text-color" href="<?php echo $category->getURL(); ?>" title="<?php echo $category->getName(); ?>"><?php echo $category->getName(); ?></a></h5>
            	        <?php if($category->getThumbnail()): ?>
                	       <a href="<?php echo $category->getURL(); ?>" title="<?php echo $category->getName(); ?>"><img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'. $category->getThumbnail(); ?>" alt=""  /></a>
            	        <?php endif; ?> 
            	        <!--<div class="bottom">
            		        <?php // show subs ?>
            		        <?php $newSubCategories = explode(',', $category->getChildren()); ?>
            		        <ul> 
                		        <?php foreach ($newSubCategories as $newSubCategoryId): ?>
                			        <?php $newCategory = Mage::getModel('catalog/category')->load($newSubCategoryId); ?>
                    		        <li class="subCat">
                    			        <a href="<?php echo $newCategory->getURL(); ?>" class="categoryLink" title="<?php echo $newCategory->getName(); ?>"><?php echo $newCategory->getName(); ?></a>
                    		        </li>
                		        <?php endforeach; ?>
            		        </ul>
            	        </div>
            	        <a class="viewAll" href="<?php echo $category->getURL(); ?>" title="<?php echo $category->getName(); ?>"><span>Check All Categories</span></a>-->
                    </div>
        	    </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </div> 
</div>