<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct()
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <div class="border-box-area1">
        <div class="specs-box-area1 row">
            <?php foreach ($_additional as $_data): ?>
                <div class="specs-box1 col-md-3">
                    <table class="data-table" id="product-attribute-specs-table1">
                        <col width="20%" />
                        <tbody>
                            <tr> 
                                <th class="label1"><?php echo $this->escapeHtml($this->__($_data['label'])) ?></th>   
                            </tr>
                            <tr>
                                <td class="data1"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                            </tr>
                        </tbody>   
                    </table>
                    <script type="text/javascript">decorateTable('product-attribute-specs-table1')</script>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;?>