<div class="ajaxlogin-login">
    <div class="account-login">

        <div class="<?php echo $this->_getColSet(); ?> ajaxlogin-login-lower">
            <?php if($this->_googleEnabled()): ?>
                <div class="<?php echo $this->_getButtCol(); ?> ajaxlogin-login-lower-google">
                    <div class="buttons-set">
                        <?php echo $this->getChildHtml('ajaxlogin_google_login_button'); ?>
                    </div>
                </div>
            <?php endif; ?>
            <?php if($this->_facebookEnabled()): ?>
                <div class="<?php echo $this->_getButtCol(); ?> ajaxlogin-login-lower-facebook">
                    <div class="buttons-set">
                        <?php echo $this->getChildHtml('ajaxlogin_checkout_facebook_button'); ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
