<div class="account-login">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form onsubmit="formSubmitByAjax('g-form-login', '<?php echo $this->getUrl('ajaxlogin/account/szLogin')?>');return false;" method="post" id="g-form-login">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="col-set">
            <div class="col registered-users">
                <div class="login-content">
                    <!-- vinu changes for gap placement after title extra div added (29-8-15) -->
                    <div class="vbox-head">
                        <div class="sign-box-head row">
                            <span class="f-right new-user">
                                <span>
                                    <?php echo $this->__('New User? ') ?>
                                </span>
                                <a href="javascript:void(0);" id="sign-up"><?php echo $this->__('Sign Up') ?></a>
                            </span>
                            <div class="popup-title f-left"><?php echo $this->__('Log In') ?></div>
                        </div>
                    </div>
                    <!-- changes end -->
                    <ul class="form-list">
                        <li>
                            <div class="pop-form row">
                                <label for="email"><?php echo $this->__('Email') ?></label>
                                <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="txtbx txtbx-wid0  required-entry validate-email" placeholder="abc@example.com" title="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </li>
                        <li>
                            <div class="pop-form row">
                                <label for="pass"><?php echo $this->__('Password') ?></label>
                                <input type="password" name="login[password]" class="txtbx txtbx-wid0 required-entry validate-password" id="pass" placeholder="Enter Password" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                        <li>
                            <div class="pop-form row">
                                <button id="signin-btn" class="clr-fff btn-common2 sign-btn" type="submit"><?php echo $this->__('Login') ?></button>
                                <a href="javascript:void(0)" class="fs11" id="frgt_pass"><?php echo $this->__('Forgot Password?')?></a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
        //]]>
    </script>
</div>

<!-- vinu changes for OR division (29-8-15) -->
<div class="pos-rel orBlock">- OR -</div>
<!-- changes end -->

<!-- vinu changes for social login buttons (30-8-15) -->
<div class="ajaxlogin-login-lower">
    <?php if($this->_googleEnabled()): ?>
        <?php echo $this->getChildHtml('ajaxlogin_google_login_button'); ?>
    <?php endif; ?>
    <?php if($this->_facebookEnabled()): ?>
        <?php echo $this->getChildHtml('ajaxlogin_facebook_login_button'); ?>
    <?php endif; ?>
</div> 
<!-- changes end -->     